// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAk8URySRgRu-xmKnaDDL-ZCDSYps1QtPo',
    appId: '1:1002940183133:web:3b6388af372b66fd08d3b4',
    messagingSenderId: '1002940183133',
    projectId: 'nursingpdq',
    authDomain: 'nursingpdq.firebaseapp.com',
    storageBucket: 'nursingpdq.firebasestorage.app',
    measurementId: 'G-Z7YW2TSHTT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDm5uw6GFc6BT8I4xJ0lcSdxltgaoJnp7k',
    appId: '1:1002940183133:android:461a23157b59d97f08d3b4',
    messagingSenderId: '1002940183133',
    projectId: 'nursingpdq',
    storageBucket: 'nursingpdq.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpIDMxufxro_VnyZLx9t5kQbSbzFRCO_Y',
    appId: '1:1002940183133:ios:b36664c1ddabecdf08d3b4',
    messagingSenderId: '1002940183133',
    projectId: 'nursingpdq',
    storageBucket: 'nursingpdq.firebasestorage.app',
    iosBundleId: 'com.example.nursingpdq',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpIDMxufxro_VnyZLx9t5kQbSbzFRCO_Y',
    appId: '1:1002940183133:ios:e533a228b7fa974308d3b4',
    messagingSenderId: '1002940183133',
    projectId: 'nursingpdq',
    storageBucket: 'nursingpdq.firebasestorage.app',
    iosBundleId: 'com.kauvery.pdq',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAk8URySRgRu-xmKnaDDL-ZCDSYps1QtPo',
    appId: '1:1002940183133:web:1ce7cf72f0dc766c08d3b4',
    messagingSenderId: '1002940183133',
    projectId: 'nursingpdq',
    authDomain: 'nursingpdq.firebaseapp.com',
    storageBucket: 'nursingpdq.firebasestorage.app',
    measurementId: 'G-X0JCME71RD',
  );

}